config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: 'create'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  get 'tasks/:id', to: 'tasks#show', as: 'show'
  patch 'tasks/:id', to: 'tasks#update', as: 'task'
  delete 'tasks/:id', to: 'tasks#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_permitted_params)
    @task.save
    redirect_to(show_path(@task.id))
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_permitted_params)
    redirect_to show_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_permitted_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task do |form| %>
  <%= form.label :title, "Title:" %>
  <%= form.text_field :title %>
  <%= form.label :details, "Details:" %>
  <%= form.text_field :details %>
  <%= form.label :completed, "Completed:" %>
  <%= form.check_box :completed %>
  <%= form.submit "Update"%>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul>

<% @tasks.each do |task| %>

<li>
  <% if task.completed? %>
    <i class="fa-regular fa-square-check"></i>
  <% else %>
    <i class="fa-regular fa-square"></i>
  <% end %>    <%= link_to "#{task.title}", show_path(task.id)%>

    <%= link_to destroy_path(task.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
       <i class="fa fa-trash fa-2x"></i>
    <% end %>

</li>

<% end %>
<p><%= link_to "Add new task", create_path%></p>
</ul>

app/views/tasks/new.html.erb
<%= form_with model: @task do |form| %>
  <%= form.label :title, "Title:" %>
  <%= form.text_field :title %>
  <%= form.label :details, "Details:" %>
  <%= form.text_field :details %>
  <%= form.submit "Create"%>
<% end %>

app/views/tasks/show.html.erb
<h1> <%=@task.title%></h1>
<p> <%=@task.details %> </p>
<p> <%=@task.completed %> </p>

<div class=btn></div>

<%# <form method="get" class="button_to" edit_path>
  <div><input  value="Update" type="submit" /></div>
</form> %>
<%= link_to "Edit", edit_path(@task), class: "btn btn-primary" %>